<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robocar_bringup</name>
  <version>0.1.0</version>
  <description>Launch et configs de la Robocar, une brique par launch.</description>
  <maintainer email="jason.chemin@epitech.eu">Jason Chemin</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>robocar_description</exec_depend>
  <!-- control -->
  <exec_depend>joy</exec_depend>
  <exec_depend>joy_teleop</exec_depend>
  <exec_depend>ackermann_mux</exec_depend>
  <exec_depend>vesc_driver</exec_depend>
  <exec_depend>vesc_ackermann</exec_depend>
  <!-- capteurs -->
  <exec_depend>ldlidar_stl_ros2</exec_depend>
  <exec_depend>depthai_ros_driver</exec_depend>
  <exec_depend>image_transport_plugins</exec_depend>
  <exec_depend>robocar_camera</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
